---
hammer_base_package: ruby-hammer-cli
hammer_plugin_prefix: ruby-hammer-cli-
hammer_packages: >-
  {{ [hammer_base_package] + (hammer_default_plugins + hammer_plugins) | map('regex_replace', '^', hammer_plugin_prefix) | list }}
