---
postgresql_container_image: quay.io/sclorg/postgresql-13-c9s
postgresql_container_tag: "latest"
postgresql_container_name: postgresql
postgresql_network: host
postgresql_restart_policy: always

postgresql_data_dir: /var/lib/pgsql/data

postgresql_admin_password: "CHANGEME"

postgresql_max_connections: "{{ (postgresql_connection_count | int / 500) | round(0, 'ceil') | int * 500 }}"
postgresql_shared_buffers_in_mb: "{{ (ansible_facts['memtotal_mb'] / 8 / 512) | round(0, 'ceil') | int * 512 }}"
postgresql_shared_buffers: "{{ postgresql_shared_buffers_in_mb }}MB"
postgresql_effective_cache_size: "{{ postgresql_shared_buffers_in_mb | int * 2 }}MB"
