---
collections:
  - name: https://github.com/ansible-collections/ansible.posix
    type: git
  - name: https://github.com/ansible-collections/community.crypto
    type: git
  - name: https://github.com/ansible-collections/community.general
    type: git
  - name: https://github.com/ansible-collections/community.postgresql
    type: git
  - name: https://github.com/containers/ansible-podman-collections
    type: git
  - name: https://github.com/theforeman/forklift
    type: git
  - name: https://github.com/theforeman/foreman-ansible-modules/releases/download/v5.12.0/theforeman-foreman-5.12.0.tar.gz
    type: url
