---
- name: Manage virtual machines for development and testing
  gather_facts: false
  hosts:
    - localhost
  tasks:
    - name: Start virtual machines
      when: vm_action == 'start'
      block:
        - name: Run vagrant up
          ansible.builtin.command:
            cmd: "vagrant up {{ vms | default('quadlet client') }}"
          args:
            chdir: "{{ inventory_dir }}/../"
          register: vagrant_up
          changed_when: false
          until: >-
            vagrant_up.rc == 0 or
            'The requested URL returned error: 502' not in
            (vagrant_up.stdout ~ vagrant_up.stderr) or
            (
              'There was an error while downloading the metadata for this box.' not in
              (vagrant_up.stdout ~ vagrant_up.stderr) and
              'There was an error downloading the file from the given URL.' not in
              (vagrant_up.stdout ~ vagrant_up.stderr)
            )
          retries: 3
          delay: 15

        - name: Force vagrant provision
          ansible.builtin.command:
            cmd: "vagrant provision {{ vms | default() }}"
          args:
            chdir: "{{ inventory_dir }}/../"
          changed_when: false

        - name: Create local_vagrant inventory
          ansible.builtin.command:
            cmd: ../../scripts/vagrant.py --yaml
          register: inventory_output
          changed_when: false

        - name: Write inventory
          ansible.builtin.copy:
            dest: "{{ inventory_dir }}/local_vagrant"
            content: "{{ inventory_output.stdout }}\n"
            mode: "0664"

    - name: Stop virtual machines
      when: vm_action == 'stop'
      block:
        - name: Run vagrant destroy
          ansible.builtin.command:
            cmd: "vagrant destroy -f {{ vms | default() }}"
          args:
            chdir: "{{ inventory_dir }}/../"
          changed_when: false

        - name: Remove vagrant inventory
          ansible.builtin.file:
            state: absent
            path: "{{ inventory_dir }}/local_vagrant"
