---
- name: Deploy IOP Network
  ansible.builtin.include_role:
    name: iop_network

- name: Deploy IOP Kafka service
  ansible.builtin.include_role:
    name: iop_kafka

- name: Deploy IOP Ingress service
  ansible.builtin.include_role:
    name: iop_ingress

- name: Deploy IOP Puptoo service
  ansible.builtin.include_role:
    name: iop_puptoo

- name: Deploy IOP Yuptoo service
  ansible.builtin.include_role:
    name: iop_yuptoo

- name: Deploy IOP Engine service
  ansible.builtin.include_role:
    name: iop_engine

- name: Deploy IOP Gateway service
  ansible.builtin.include_role:
    name: iop_gateway

- name: Register IOP Gateway as smart proxy
  theforeman.foreman.smart_proxy:
    name: "iop-gateway"
    url: "https://localhost:24443"
    server_url: "{{ iop_core_foreman_url }}"
    oauth1_consumer_key: "{{ iop_core_foreman_oauth_consumer_key }}"
    oauth1_consumer_secret: "{{ iop_core_foreman_oauth_consumer_secret }}"
    validate_certs: false

- name: Deploy IOP Inventory service
  ansible.builtin.include_role:
    name: iop_inventory
  vars:
    iop_inventory_postgresql_admin_password: "{{ iop_core_postgresql_admin_password }}"

- name: Deploy IOP Advisor service
  ansible.builtin.include_role:
    name: iop_advisor
  vars:
    iop_advisor_fdw_remote_database_name: "{{ iop_core_inventory_database_name }}"
    iop_advisor_fdw_remote_database_user: "{{ iop_core_inventory_database_user }}"
    iop_advisor_fdw_remote_database_password: "{{ iop_core_inventory_database_password }}"

- name: Deploy IOP Remediation service
  ansible.builtin.include_role:
    name: iop_remediation

- name: Deploy IOP CVE Map Downloader
  ansible.builtin.include_role:
    name: iop_cvemap_downloader

- name: Deploy IOP VEX Downloader
  ansible.builtin.include_role:
    name: iop_vex_downloader

- name: Deploy IOP VMAAS service
  ansible.builtin.include_role:
    name: iop_vmaas

- name: Deploy IOP Vulnerability service
  ansible.builtin.include_role:
    name: iop_vulnerability
  vars:
    iop_vulnerability_fdw_remote_database_name: "{{ iop_core_inventory_database_name }}"
    iop_vulnerability_fdw_remote_database_user: "{{ iop_core_inventory_database_user }}"
    iop_vulnerability_fdw_remote_database_password: "{{ iop_core_inventory_database_password }}"

- name: Deploy IOP Inventory Frontend
  ansible.builtin.include_role:
    name: iop_inventory_frontend

- name: Deploy IOP Advisor Frontend
  ansible.builtin.include_role:
    name: iop_advisor_frontend

- name: Deploy IOP Vulnerability Frontend
  ansible.builtin.include_role:
    name: iop_vulnerability_frontend
