---
- name: Install foreman-installer package
  ansible.builtin.package:
    name: foreman-installer-katello

- name: Create foreman-certs scenarios directory
  ansible.builtin.file:
    path: /usr/share/foreman-installer/foreman-certs/scenarios.d
    state: directory
    mode: '0755'

- name: Deploy foreman-certs binary
  ansible.builtin.copy:
    src: foreman-certs
    dest: /usr/sbin/foreman-certs
    mode: '0755'

- name: Deploy foreman-certs scenario config
  ansible.builtin.copy:
    src: foreman-certs.yaml
    dest: /usr/share/foreman-installer/foreman-certs/scenarios.d/foreman-certs.yaml
    mode: '0644'

- name: Deploy foreman-certs answers file
  ansible.builtin.copy:
    src: foreman-certs-answers.yaml
    dest: /usr/share/foreman-installer/foreman-certs/scenarios.d/foreman-certs-answers.yaml
    mode: '0644'

- name: Install puppet-strings gem
  ansible.builtin.command: /opt/puppetlabs/puppet/bin/gem install openvox-strings
  changed_when: false

- name: Generate certs
  ansible.builtin.command: foreman-certs --apache true --foreman true --candlepin true --iop true
  changed_when: false

- name: Create installer scenarios directory
  ansible.builtin.file:
    path: /etc/foreman-installer/scenarios.d
    state: directory
    mode: '0755'

- name: Place answers file fixture
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../../../tests/fixtures/installer-answers/katello-answers.yaml"
    dest: /etc/foreman-installer/scenarios.d/katello-answers.yaml
    mode: '0600'

- name: Place scenario file fixture
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../../../tests/fixtures/installer-answers/last_scenario.yaml"
    dest: /etc/foreman-installer/scenarios.d/last_scenario.yaml
    mode: '0644'
