---
- name: Pull images
  hosts:
    - quadlet
  vars_files:
    - "../../vars/defaults.yml"
    - "../../vars/flavors/{{ flavor }}.yml"
    - "../../vars/images.yml"
    - "../../vars/base.yaml"
  become: true
  roles:
    - role: pre_install
  post_tasks:
    - name: Deploy core image units
      ansible.builtin.include_role:
        name: "{{ item }}"
        tasks_from: image.yaml
      loop:
        - foreman
        - candlepin
        - pulp
        - redis

    - name: Deploy database image units
      ansible.builtin.include_role:
        name: postgresql
        tasks_from: image.yaml
      when: database_mode == 'internal'

    - name: Deploy proxy image units
      ansible.builtin.include_role:
        name: foreman_proxy
        tasks_from: image.yaml
      when: "'foreman-proxy' in enabled_features"

    - name: Deploy IOP image units
      ansible.builtin.include_role:
        name: "{{ item }}"
        tasks_from: image.yaml
      loop:
        - iop_kafka
        - iop_ingress
        - iop_puptoo
        - iop_yuptoo
        - iop_engine
        - iop_gateway
        - iop_inventory
        - iop_advisor
        - iop_remediation
        - iop_vmaas
        - iop_vulnerability
        - iop_advisor_frontend
        - iop_inventory_frontend
        - iop_vulnerability_frontend
      when: "'iop' in enabled_features"

    - name: Pull images
      ansible.builtin.include_role:
        name: images
        tasks_from: pull.yaml
