---
- name: Run post install tasks
  ansible.builtin.include_tasks: "{{ flavor }}.yaml"

- name: Check for unrecognized Smart Proxy features
  ansible.builtin.include_tasks: smart_proxy_features_check.yaml
  vars:
    foreman_server_url: "{{ foreman_url }}"
    foreman_ca_path: "{{ foreman_ca_certificate }}"
