---
- name: Deploy iop-engine image unit
  ansible.builtin.include_role:
    name: images
    tasks_from: deploy_image.yaml
  vars:
    images_definition:
      name: iop-engine
      image: "{{ iop_engine_container_image }}:{{ iop_engine_container_tag }}"
