httpd_ssl_dir: /etc/pki/httpd
httpd_pulp_api_backend: http://localhost:24817
httpd_pulp_content_backend: http://localhost:24816
httpd_foreman_backend: http://localhost:3000
httpd_pub_dir: /var/www/html/pub

# MPM event module defaults (matching puppet-apache base values)
httpd_server_limit: 25
httpd_start_servers: 2
httpd_min_spare_threads: 16
httpd_max_spare_threads: 32
httpd_threads_per_child: 16
httpd_thread_limit: 64
httpd_listen_backlog: 511

# External authentication configuration
httpd_external_authentication: "{{ external_authentication | default(None) }}"
httpd_ipa_manage_sssd: true
httpd_ipa_keytab: /etc/httpd/conf/http.keytab
httpd_ipa_pam_service: "{{ external_authentication_pam_service | default('foreman') }}"
httpd_ipa_gssapi_local_name: true
