---
variables:
  foreman_initial_admin_username:
    help: Initial username for the admin user.
    parameter: --initial-admin-username
  foreman_initial_admin_password:
    help: Initial password for the admin user.
    parameter: --initial-admin-password
  foreman_initial_organization:
    help: Name of an initial organization.
    parameter: --initial-organization
  foreman_initial_location:
    help: Name of an initial location.
    parameter: --initial-location
  foreman_puma_workers:
    help: Number of workers for Puma.
  server_aliases:
    help: Server alias. Used for Subject Alternative Names in generated certificates and accepted server names. Can be specified multiple times.
    action: append_unique
    type: FQDN
    parameter: --server-alias
