---
help: |
  Setup hammer

variables:
  enable_kerberos_authentication:
    help: Whether to enable Kerberos/negotiate authentication for Hammer CLI
    action: store_true

include:
  - _certificate_source
