# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: foremanctl.spec

upstream_package_name: foremanctl
downstream_package_name: foremanctl

srpm_build_deps:
  - ansible-core
  - make
  - wget

actions:
  post-upstream-clone:
    - "wget https://raw.githubusercontent.com/theforeman/foreman-packaging/rpm/develop/packages/foreman/foremanctl/foremanctl.spec -O foremanctl.spec"
  create-archive:
    - make dist
    - bash -c 'ls -1t foremanctl-*.tar.gz | head -n1'

jobs:
  - &copr
    job: copr_build
    trigger: pull_request
    targets:
      - rhel-9

  - <<: *copr
    trigger: commit
    branch: master
    owner: '@theforeman'
    project: foremanctl
