# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: foremanctl.spec

upstream_package_name: foremanctl
downstream_package_name: foremanctl

srpm_build_deps:
  - ansible-core
  - make

actions:
  create-archive:
    - make dist
    - bash -c 'ls -1t foremanctl-*.tar.gz | head -n1'

jobs:
  - &copr
    job: copr_build
    trigger: pull_request
    targets:
      - rhel-9

  - <<: *copr
    trigger: commit
    branch: develop
    owner: theforeman
    project: foremanctl
