#!/bin/bash

if [[ -z "${GITHUB_ACTIONS}" ]]; then
  python -m venv .venv
  source .venv/bin/activate
fi
pip install -r src/requirements.txt
pip install -r development/requirements.txt
ANSIBLE_COLLECTIONS_PATH=./build/collections/foremanctl ansible-galaxy install -r src/requirements.yml
ANSIBLE_COLLECTIONS_PATH=./build/collections/forge ansible-galaxy install -r development/requirements.yml

printf "\n\nSetup complete.\n"
printf "Activate the virtualenv 'source .venv/bin/activate'.\n"
printf "Then run the cli using './foremanctl'.\n"
