---
- name: Deploy pulp image unit
  ansible.builtin.include_role:
    name: images
    tasks_from: deploy_image.yaml
  vars:
    images_definition:
      name: pulp
      image: "{{ pulp_container_image }}:{{ pulp_container_tag }}"
