---
- name: Restart CPE download timer
  ansible.builtin.systemd:
    name: iop-cpe-download.timer
    state: restarted

- name: Restart CPE download path
  ansible.builtin.systemd:
    name: iop-cpe-download.path
    state: restarted
