---
cloud_connector_url: "{{ foreman_url }}"
cloud_connector_user: "{{ foreman_initial_admin_username }}"
cloud_connector_password: "{{ foreman_initial_admin_password }}"
cloud_connector_config_file: /etc/rhc/workers/foreman_rh_cloud.toml
cloud_connector_validate_certs: true
