FROM quay.io/centos/centos:stream9

ARG FOREMAN_VERSION=nightly
ARG KATELLO_VERSION=nightly
ARG FOREMAN_PROXY_PLUGINS="pulp"

RUN dnf upgrade -y && dnf install -y https://yum.theforeman.org/releases/${FOREMAN_VERSION}/el9/x86_64/foreman-release.rpm https://yum.theforeman.org/katello/${KATELLO_VERSION}/katello/el9/x86_64/katello-repos-latest.rpm && dnf install foreman-proxy -y

RUN for PLUGIN in ${FOREMAN_PROXY_PLUGINS}; do echo $PLUGIN; dnf install -y "foreman-proxy-plugin-$PLUGIN"; echo "gem 'smart_proxy_$PLUGIN' if ENV.fetch('FOREMAN_PROXY_ENABLED_PLUGINS', '').split.include?('$PLUGIN') || ENV.fetch('FOREMAN_PROXY_ENABLED_PLUGINS', nil).nil?" > /usr/share/foreman-proxy/bundler.d/$PLUGIN.rb; done

USER foreman-proxy
WORKDIR /usr/share/foreman-proxy
ENV MALLOC_ARENA_MAX=2
CMD /usr/share/foreman-proxy/bin/smart-proxy
EXPOSE 8443/tcp
