---
variables:
  log_level:
    help: Default log level for all services, unless overridden by the service-specific parameters.
    parameter: --log-level
    choices:
      - debug
      - info
      - warn
      - error
      - fatal
  foreman_proxy_log_level:
    help: Defaults to the global log level, can be set independently. Once set, it overrides --log-level and is unaffected by later changes.
    choices:
      - debug
      - info
      - warn
      - error
      - fatal
  valkey_log_level:
    help: Defaults to the global log level, can be set independently. Once set, it overrides --log-level and is unaffected by later changes.
    choices:
      - debug
      - verbose
      - notice
      - warning
      - nothing
  pulp_log_level:
    help: Defaults to the global log level, can be set independently. Once set, it overrides --log-level and is unaffected by later changes.
    parameter: --pulp-log-level
    choices:
      - debug
      - info
      - warning
      - error
      - critical
