---
variables:
  log_level:
    help: Default log level for all services.
    parameter: --log-level
    choices:
      - debug
      - info
      - warn
      - error
      - fatal
  foreman_proxy_log_level:
    help: Log level for Foreman Proxy. Defaults to the global log level.
    choices:
      - debug
      - info
      - warn
      - error
      - fatal
  valkey_log_level:
    help: Log level for Valkey.
    choices:
      - debug
      - verbose
      - notice
      - warning
      - nothing
