---
- name: Install foreman-certificate-check
  ansible.builtin.copy:
    src: foreman-certificate-check
    dest: /usr/local/bin/foreman-certificate-check
    mode: '0755'

- name: Check certificates
  ansible.builtin.command:
    argv:
      - "/usr/local/bin/foreman-certificate-check"
      - "-c"
      - "{{ certificate_checks_certificate }}"
      - "-k"
      - "{{ certificate_checks_key }}"
      - "-b"
      - "{{ certificate_checks_ca }}"
  changed_when: false
  check_mode: false
