---
iop_advisor_frontend_container_image: "quay.io/iop/advisor-frontend"
iop_advisor_frontend_container_tag: "foreman-3.18"
iop_advisor_frontend_registry_auth_file: /etc/foreman/registry-auth.json
iop_advisor_frontend_assets_path: "/var/www/iop/assets/apps/advisor"
iop_advisor_frontend_source_path: "/srv/dist/."
