---
- name: Verify Subuid/Subgid Role
  hosts: all
  gather_facts: true
  tasks:
    - name: Check subuid entry exists
      ansible.builtin.command: grep "^{{ ansible_user_id }}:" /etc/subuid
      register: check_subuid_subgid_subuid
      changed_when: false
      failed_when: check_subuid_subgid_subuid.rc != 0

    - name: Check subgid entry exists
      ansible.builtin.command: grep "^{{ ansible_user_id }}:" /etc/subgid
      register: check_subuid_subgid_subgid
      changed_when: false
      failed_when: check_subuid_subgid_subgid.rc != 0
