---
variables:
  certificates_algorithm_type:
    help: Algorithm used for the keys of the generated certificates.
    parameter: --certificate-algorithm
    choices:
      - RSA
      - ECC
      - ML-DSA-87
  certificates_algorithm_rsa_size:
    help: Key size of the generated certificates. Only applies to RSA.
    parameter: --certificate-algorithm-rsa-size
  certificates_algorithm_ecc_curve:
    help: Elliptic curve of the generated certificates. Only applies to ECC.
    parameter: --certificate-algorithm-ecc-curve

constraints:
  forbidden_if:
    - ['certificates_algorithm_type', 'ECC', ['certificates_algorithm_rsa_size']]
    - ['certificates_algorithm_type', 'ML-DSA-87', ['certificates_algorithm_rsa_size']]
    - ['certificates_algorithm_type', 'RSA', ['certificates_algorithm_ecc_curve']]
    - ['certificates_algorithm_type', 'ML-DSA-87', ['certificates_algorithm_ecc_curve']]
