---
- name: Resize disk and filesystem
  hosts: all
  become: true
  tasks:
    - name: Find root partition
      ansible.builtin.shell: set -o pipefail && df --output=source,fstype / | tail -n 1
      register: root_partition
      changed_when: false

    - name: Install cloud-utils-growpart package
      ansible.builtin.package:
        name: cloud-utils-growpart
      when: ansible_os_family == 'RedHat'

    - name: Install cloud-guest-utils package
      ansible.builtin.package:
        name: cloud-guest-utils
      when: ansible_os_family == 'Debian'

    - name: Install e2fsprogs package
      ansible.builtin.package:
        name: e2fsprogs
      when: '"ext4" in root_partition.stdout'

    - name: Extend partition
      ansible.builtin.command: growpart {{ root_partition.stdout | regex_replace('^(/dev/[sv]da)(\d+) .+$', '\1 \2') }}
      register: growpart_output
      changed_when: '"CHANGED" in growpart_output.stdout'
      failed_when:
        - growpart_output.rc != 0
        - '"NOCHANGE" not in growpart_output.stdout'

    - name: Grow XFS filesystem
      ansible.builtin.command: xfs_growfs -d /
      when: '"xfs" in root_partition.stdout'
      changed_when: true

    - name: Grow ext4 filesystem
      ansible.builtin.command: resize2fs {{ root_partition.stdout.split(' ')[0] }}
      when: '"ext4" in root_partition.stdout'
      changed_when: true

    - name: Grow btrfs filesystem
      ansible.builtin.command: btrfs filesystem resize max /
      when: '"btrfs" in root_partition.stdout'
      changed_when: true
