---
- name: Install cvemap download script
  ansible.builtin.copy:
    src: iop-cvemap-download.sh
    dest: /usr/local/bin/iop-cvemap-download.sh
    owner: root
    group: root
    mode: '0755'

- name: Create cvemap download service unit
  ansible.builtin.copy:
    dest: /etc/systemd/system/iop-cvemap-download.service
    content: |
      [Unit]
      Description=Manages cvemap.xml for IoP Vulnerability
      After=network-online.target iop-core-gateway.service
      Wants=network-online.target iop-core-gateway.service

      [Service]
      Type=oneshot
      ExecStart=/usr/local/bin/iop-cvemap-download.sh '{{ iop_cvemap_downloader_base_url }}' '{{ iop_cvemap_downloader_output_dir }}/{{ iop_cvemap_downloader_relative_path }}'
      User=root
      Group=root
    mode: '0644'

- name: Create cvemap download timer unit
  ansible.builtin.template:
    src: iop-cvemap-download.timer.j2
    dest: /etc/systemd/system/iop-cvemap-download.timer
    mode: '0644'
  notify: Restart cvemap download timer

- name: Create cvemap download path unit
  ansible.builtin.copy:
    src: iop-cvemap-download.path
    dest: /etc/systemd/system/iop-cvemap-download.path
    mode: '0644'
  notify: Restart cvemap download path

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Enable and start cvemap download timer
  ansible.builtin.systemd:
    name: iop-cvemap-download.timer
    enabled: true
    state: started

- name: Enable and start cvemap download path watcher
  ansible.builtin.systemd:
    name: iop-cvemap-download.path
    enabled: true
    state: started
