---
- name: 'Setup certificate directory'
  ansible.builtin.include_tasks: setup.yml

- name: 'Create CA key password file'
  ansible.builtin.copy:
    content: "{{ certificates_ca_password }}"
    dest: "{{ certificates_ca_directory_keys }}/ca.pwd"
    force: false
    owner: root
    group: root
    mode: '0600'
  no_log: true

- name: 'Creating CA certificate and key'
  ansible.builtin.command: >
    openssl req -new
      -x509
      -nodes
      -extensions v3_ca
      -days 7300
      -config "{{ certificates_ca_directory }}/openssl.cnf"
      -subj "{{ certificates_ca_subject }}"
      -keyout "{{ certificates_ca_directory_keys }}/ca.key"
      -out "{{ certificates_ca_directory_certs }}/ca.crt"
      -passout "file:{{ certificates_ca_directory_keys }}/ca.pwd"
  args:
    creates: "{{ certificates_ca_directory_certs }}/ca.crt"

- name: 'Copy CA as server CA certificate'
  ansible.builtin.copy:
    src: "{{ certificates_ca_directory_certs }}/ca.crt"
    dest: "{{ certificates_ca_directory_certs }}/server-ca.crt"
    remote_src: true
    force: false
    mode: '0444'

- name: 'Create CA bundle'
  ansible.builtin.copy:
    src: "{{ certificates_ca_directory_certs }}/ca.crt"
    dest: "{{ ca_bundle }}"
    remote_src: true
    force: false
    mode: '0444'
