---
- name: Check path to auth bundle tar file exists
  ansible.builtin.stat:
    path: "{{ auth_bundle }}"
  register: _certificates_tar_file_path
  delegate_to: localhost
  become: false

- name: Fail if path to auth bundle tar file does not exist
  ansible.builtin.fail:
    msg: "Path to auth bundle tar file not found: {{ auth_bundle }}"
  when: not _certificates_tar_file_path.stat.exists

- name: Extract certificates from bundle
  ansible.builtin.unarchive:
    src: "{{ auth_bundle }}"
    dest: "{{ certificates_ca_directory }}"
    exclude:
      - oauth
      - oauth/*

- name: Extract OAuth credentials from bundle
  ansible.builtin.unarchive:
    src: "{{ auth_bundle }}"
    dest: "{{ certificates_oauth_directory | dirname }}"
    exclude:
      - certs
      - certs/*
      - private
      - private/*
