---
- name: Check if installer certificates exist
  ansible.builtin.stat:
    path: /root/ssl-build/katello-default-ca.crt
  register: certificates_installer_ca

- name: Normalize installer certificates
  ansible.builtin.include_tasks: normalize.yml
  when: certificates_installer_ca.stat.exists

- name: Generate CA certificate
  ansible.builtin.include_tasks: ca.yml
  when:
    - certificates_ca
    - not certificates_installer_ca.stat.exists

- name: Apply custom server certificates
  ansible.builtin.include_tasks: custom.yml
  when: certificates_custom_server_certificate is defined

- name: Issue host certificates
  ansible.builtin.include_tasks: issue.yml
  when: certificates_hostnames is defined
  with_items: "{{ certificates_hostnames }}"
  loop_control:
    loop_var: certificates_hostname
