---
- name: Check path to certificate tar file exists
  ansible.builtin.stat:
    path: "{{ certificate_tar_file }}"
  register: _certificate_tar_file_path

- name: Fail if path to certificate tar file does not exist
  ansible.builtin.fail:
    msg: "Path to certificate tar file not found: {{ certificate_tar_file }}"
  when: not _certificate_tar_file_path.stat.exists

- name: Extract certificate bundle
  ansible.builtin.unarchive:
    src: "{{ certificate_tar_file }}"
    dest: "{{ certificates_ca_directory }}"
    remote_src: true
    extra_opts:
      - --strip-components=1

- name: Set private key directory permissions
  ansible.builtin.file:
    path: "{{ certificates_ca_directory_keys }}"
    state: directory
    mode: '0750'

- name: Restrict private key files
  ansible.builtin.shell:
    cmd: "chmod 0640 {{ certificates_ca_directory_keys }}/*"

- name: Create CA bundle
  ansible.builtin.assemble:
    src: "{{ certificates_ca_directory_certs }}"
    dest: "{{ certificates_ca_directory_certs }}/ca-bundle.crt"
    regexp: '(ca|server-ca)\.crt$'
    mode: '0444'
