---
certificates_hostnames:
  - "{{ ansible_facts['fqdn'] }}"
  - localhost

certificates_ca_password_file: "{{ obsah_state_path }}/certificates-ca-password"
certificates_ca_password: "{{ lookup('ansible.builtin.password', certificates_ca_password_file, chars=['ascii_letters', 'digits']) }}"
candlepin_oauth_secret_file: "{{ obsah_state_path }}/candlepin-oauth-secret"
candlepin_oauth_secret: "{{ lookup('ansible.builtin.password', candlepin_oauth_secret_file, chars=['ascii_letters', 'digits'], length=32) }}"

candlepin_ca_key_password: "{{ ca_key_password }}"
candlepin_ca_key: "{{ ca_key }}"
candlepin_ca_certificate: "{{ ca_certificate }}"
candlepin_tomcat_key: "{{ localhost_key }}"
candlepin_tomcat_certificate: "{{ localhost_certificate }}"
candlepin_client_key: "{{ client_key }}"
candlepin_client_certificate: "{{ client_certificate }}"

foreman_ca_certificate: "{{ ca_bundle }}"
foreman_client_key: "{{ client_key }}"
foreman_client_certificate: "{{ client_certificate }}"
foreman_plugins: "{{ enabled_features | features_to_foreman_plugins }}"
foreman_name: "{{ ansible_facts['fqdn'] }}"
foreman_url: "https://{{ foreman_name }}"

httpd_server_ca_certificate: "{{ server_ca_certificate }}"
httpd_client_ca_certificate: "{{ client_ca_certificate }}"
httpd_server_certificate: "{{ server_certificate }}"
httpd_server_key: "{{ server_key }}"
httpd_enabled_pulp_snippets: "{{ ['pypi'] if 'pulp_python' in pulp_plugins else [] }}"
httpd_foreman_url: "{{ foreman_url }}"
httpd_foreman_proxy_url: "{{ foreman_proxy_url }}"
httpd_pulp_trusted_hosts:
  - "{{ foreman_name }}"

pulp_storage_path: /var/lib/pulp
pulp_content_origin: "https://{{ ansible_facts['fqdn'] }}"
pulp_pulp_url: "https://{{ ansible_facts['fqdn'] }}"
pulp_plugins: "{{ enabled_features | select('contains', 'content/') | map('replace', 'content/', 'pulp_') | list }}"
pulp_rhsm_url: "{{ foreman_proxy_foreman_server_url }}/rhsm"
pulp_foreman_url: "{{ foreman_proxy_foreman_server_url }}"
pulp_foreman_ca_certificate: "{{ foreman_ca_certificate }}"
pulp_foreman_oauth_consumer_key: "{{ foreman_proxy_oauth_consumer_key }}"
pulp_foreman_oauth_consumer_secret: "{{ foreman_proxy_oauth_consumer_secret }}"

hammer_ca_certificate: "{{ server_ca_certificate }}"
hammer_plugins: "{{ enabled_features | features_to_hammer_plugins }}"
hammer_foreman_server_url: "{{ foreman_url }}"

foreman_proxy_plugins: "{{ enabled_features | features_to_foreman_proxy_plugins }}"
foreman_proxy_foreman_server_url: "{{ foreman_url }}"
foreman_proxy_foreman_ca_certificate: "{{ foreman_ca_certificate }}"
foreman_proxy_oauth_consumer_key: "{{ foreman_oauth_consumer_key }}"
foreman_proxy_oauth_consumer_secret: "{{ foreman_oauth_consumer_secret }}"
foreman_proxy_trusted_hosts:
  - "{{ foreman_name }}"

iop_core_foreman_url: "{{ foreman_url }}"
iop_core_foreman_oauth_consumer_key: "{{ foreman_oauth_consumer_key }}"
iop_core_foreman_oauth_consumer_secret: "{{ foreman_oauth_consumer_secret }}"

backup_foreman_oauth_consumer_key: "{{ foreman_oauth_consumer_key }}"
backup_foreman_oauth_consumer_secret: "{{ foreman_oauth_consumer_secret }}"
backup_foreman_ca_certificate: "{{ foreman_ca_certificate }}"
backup_foreman_client_certificate: "{{ foreman_client_certificate }}"
backup_foreman_client_key: "{{ foreman_client_key }}"
