---
- name: Enable foreman-installer PR 935 Copr repo
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: packit/theforeman-foreman-installer-935
    chroot: rhel-9-x86_64

- name: Install foreman-installer package
  ansible.builtin.package:
    name: foreman-installer-katello

# utilize https://github.com/theforeman/foreman-installer/pull/935
- name: Generate certs
  ansible.builtin.command: foreman-certs --apache true --foreman true --candlepin true
  changed_when: false
