---
- name: Run preflight checks
  hosts: quadlet
  gather_facts: true
  vars_files:
    - "../../vars/defaults.yml"
    - "../_vendor_overrides/server/vars.yaml"
    - "../../vars/flavors/{{ flavor }}.yml"
    - "../../vars/database.yml"
  roles:
    - role: checks
      vars:
        checks_databases: "{{ all_databases }}"
