---
- name: Run preflight checks
  hosts: quadlet
  gather_facts: true
  vars:
    flavor: katello
  vars_files:
    - "../../vars/defaults.yml"
    - "../../vars/flavors/{{ flavor }}.yml"
    - "../../vars/database.yml"
  roles:
    - role: checks
      vars:
        checks_databases: "{{ all_databases }}"
        checks_database_mode: "{{ database_mode }}"
        checks_database_host: "{{ database_host }}"
        checks_database_port: "{{ database_port }}"
        checks_postgresql_admin_password: "{{ postgresql_admin_password }}"
