#!/usr/bin/env ruby
require 'rubygems'
require 'kafo'

CONFIG_DIR = '/usr/share/foreman-installer/foreman-certs/scenarios.d/'.freeze

@result = Kafo::KafoConfigure.run
exit((@result.nil? || @result.exit_code == 2) ? 0 : @result.exit_code)
