---
- name: Restart pulp-api
  ansible.builtin.systemd:
    name: pulp-api
    state: restarted

- name: Restart pulp-content
  ansible.builtin.systemd:
    name: pulp-content
    state: restarted

- name: Restart pulp-worker
  ansible.builtin.systemd:
    daemon_reload: true
    name: "pulp-worker@{{ pulp_worker_index }}.service"
    state: restarted
  loop: "{{ range(1, pulp_worker_count | int + 1) | list }}"
  loop_control:
    loop_var: pulp_worker_index
