- name: Store CA cert to a temporary file
  when:
    - _db_item.ssl_ca is defined
    - _db_item.ssl_ca is truthy
  block:
    - name: Create temporary file
      ansible.builtin.tempfile:
        state: file
        prefix: check_database_connection_
      register: _check_database_connection_ca_cert

    - name: Write CA cert to temporary file
      ansible.builtin.copy:
        dest: "{{ _check_database_connection_ca_cert.path }}"
        src: "{{ _db_item.ssl_ca }}"
        mode: '0640'

- name: Check database connectivity to {{ _db_item.name }}
  community.postgresql.postgresql_ping:
    login_host: "{{ _db_item.host }}"
    login_user: "{{ _db_item.user }}"
    login_password: "{{ _db_item.password }}"
    login_db: "{{ _db_item.database }}"
    ca_cert: "{{ _check_database_connection_ca_cert.path | default(omit) }}"
    ssl_mode: "{{ _db_item.ssl_mode | default(omit) }}"
  register: check_database_connection_ping_result
  ignore_errors: true

- name: Delete temporary CA cert file
  when:
    - _db_item.ssl_ca is defined
    - _db_item.ssl_ca is truthy
  block:
    - name: Delete temporary file
      ansible.builtin.file:
        state: absent
        path: "{{ _check_database_connection_ca_cert.path }}"

- name: Assert database is reachable for {{ _db_item.name }}
  ansible.builtin.assert:
    that:
      - check_database_connection_ping_result.is_available
    fail_msg: >
      Cannot connect to {{ _db_item.name }} database '{{ _db_item.database }}' at {{ _db_item.host }}.
      Please verify the database host, port, name, user, and password.
      Error: {{ check_database_connection_ping_result.conn_err_msg | default('No error message available.') }}
