---
- name: Check DB
  ansible.builtin.include_tasks: check.yaml
  no_log: true
  loop: "{{ checks_databases }}"
  loop_control:
    loop_var: db_item
    label: "{{ db_item.name }}"
  when: database_mode == 'external'
