---
- name: Generate keystore
  community.crypto.openssl_pkcs12:
    action: export
    passphrase: "{{ candlepin_keystore_password }}"
    path: "/root/candlepin.keystore"
    friendly_name: 'tomcat'
    privatekey_path: "{{ candlepin_tomcat_key }}"
    certificate_path: "{{ candlepin_tomcat_certificate }}"
    other_certificates: "{{ candlepin_ca_certificate }}"
    state: present

- name: Generate truststore
  community.crypto.openssl_pkcs12:
    action: export
    passphrase: "{{ candlepin_keystore_password }}"
    path: "/root/candlepin.truststore"
    friendly_name: 'artemis-client'
    privatekey_path: "{{ candlepin_client_key }}"
    certificate_path: "{{ candlepin_client_certificate }}"
    other_certificates: "{{ candlepin_ca_certificate }}"
    state: present

- name: Create the podman secret for Candlepin CA certificate
  containers.podman.podman_secret:
    state: present
    name: candlepin-ca-cert
    path: "{{ candlepin_ca_certificate }}"
    labels:
      app: candlepin

- name: Decrypt Candlepin CA key
  ansible.builtin.command: openssl pkey -in "{{ candlepin_ca_key }}" -passin "file:{{ candlepin_ca_key_password }}"
  register: _candlepin_ca_key
  changed_when: false

- name: Create the podman secret for Candlepin CA key
  containers.podman.podman_secret:
    state: present
    name: candlepin-ca-key
    data: "{{ _candlepin_ca_key.stdout }}"
    labels:
      app: candlepin

- name: Create the podman secret for Tomcat keystore
  containers.podman.podman_secret:
    state: present
    name: candlepin-tomcat-keystore
    path: "/root/candlepin.keystore"
    labels:
      filename: candlepin.keystore
      app: tomcat

- name: Create the podman secret for Tomcat truststore
  containers.podman.podman_secret:
    state: present
    name: candlepin-tomcat-truststore
    path: "/root/candlepin.truststore"
    labels:
      filename: candlepin.truststore
      app: tomcat

- name: Create the podman secret for the keystore password
  containers.podman.podman_secret:
    state: present
    name: candlepin-tomcat-keystore-password
    data: "{{ candlepin_keystore_password }}"
    labels:
      app: tomcat
