---
- name: Create log directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /var/log/candlepin
    - /var/log/tomcat

- name: Configure certificates
  ansible.builtin.include_tasks:
    file: certs.yml

- name: Create DB URL secret
  containers.podman.podman_secret:
    state: present
    name: candlepin-db-url
    data: "jdbc:postgresql://{{ candlepin_database_host }}:{{ candlepin_database_port }}/{{ candlepin_database_name }}?sslmode={{ candlepin_database_ssl_mode }}{% if candlepin_database_ssl_ca is defined %}&sslrootcert={{ candlepin_database_ssl_ca_path }}{% endif %}"
  notify:
    - Restart candlepin

- name: Create DB URL secret
  containers.podman.podman_secret:
    state: present
    name: candlepin-db-username
    data: "{{ candlepin_database_user }}"
  notify:
    - Restart candlepin

- name: Create DB URL secret
  containers.podman.podman_secret:
    state: present
    name: candlepin-db-password
    data: "{{ candlepin_database_password }}"
  notify:
    - Restart candlepin

- name: Create DB SSL cert
  containers.podman.podman_secret:
    state: present
    name: candlepin-db-ca
    data: "{{ lookup('ansible.builtin.file', candlepin_database_ssl_ca) if candlepin_database_ssl_ca else 'empty' }}"
  notify:
    - Restart candlepin

- name: Create oauth secret
  containers.podman.podman_secret:
    state: present
    name: candlepin-oauth-secret
    data: "{{ candlepin_oauth_secret }}"
  notify:
    - Restart candlepin

- name: Pull the Candlepin container image
  containers.podman.podman_image:
    name: "{{ candlepin_container_image }}:{{ candlepin_container_tag }}"
    state: present
  environment:
    REGISTRY_AUTH_FILE: "{{ candlepin_registry_auth_file }}"

- name: Deploy Candlepin quadlet
  containers.podman.podman_container:
    name: "candlepin"
    image: "{{ candlepin_container_image }}:{{ candlepin_container_tag }}"
    state: quadlet
    network: host
    hostname: "{{ ansible_facts['hostname'] }}.local"
    secrets:
      - 'candlepin-ca-cert,target=/etc/candlepin/certs/candlepin-ca.crt,mode=0440,type=mount'
      - 'candlepin-ca-key,target=/etc/candlepin/certs/candlepin-ca.key,mode=0440,type=mount'
      - 'candlepin-tomcat-keystore,target=/etc/candlepin/certs/keystore,mode=0440,type=mount'
      - 'candlepin-tomcat-keystore-password,target=CANDLEPIN_KEYSTORE_PASSWORD,type=env'
      - 'candlepin-db-ca,target={{ candlepin_database_ssl_ca_path }},mode=0440,type=mount'
      - 'candlepin-db-url,target=CANDLEPIN_DB_URL,type=env'
      - 'candlepin-db-username,target=CANDLEPIN_DB_USERNAME,type=env'
      - 'candlepin-db-password,target=CANDLEPIN_DB_PASSWORD,type=env'
      - 'candlepin-oauth-secret,target=CANDLEPIN_OAUTH_SECRET,type=env'
    env:
      CANDLEPIN_PORT: "{{ candlepin_ssl_port }}"
    volumes:
      - /var/log/candlepin:/var/log/candlepin:Z
      - /var/log/tomcat:/var/log/tomcat:Z
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target foreman.target
        [Unit]
        PartOf=foreman.target
        Wants=redis.service postgresql.service
        After=redis.service postgresql.service
        [Service]
        TimeoutStartSec=300
    healthcheck: "curl --fail --insecure https://localhost:{{ candlepin_ssl_port }}/candlepin/status"
    sdnotify: healthy

- name: Run daemon reload to make Quadlet create the service files
  ansible.builtin.systemd:
    daemon_reload: true

- name: Flush handlers to restart services
  ansible.builtin.meta: flush_handlers

- name: Start the Candlepin Service
  ansible.builtin.systemd:
    name: candlepin
    state: started
