---
- name: Install Hammer and plugins
  ansible.builtin.package:
    name: "{{ hammer_packages }}"

- name: Configure Hammer Foreman plugin
  ansible.builtin.template:
    src: cli.modules.d-foreman.yaml.j2
    dest: /etc/hammer/cli.modules.d/foreman.yaml
    owner: root
    group: root
    mode: '0644'
