---
certificates_ca: true
certificates_ca_directory: /var/lib/foremanctl/certs
certificates_ca_directory_keys: "{{ certificates_ca_directory }}/private"
certificates_ca_directory_certs: "{{ certificates_ca_directory }}/certs"
certificates_ca_directory_requests: "{{ certificates_ca_directory }}/requests"
certificates_cnames: []
certificates_algorithm_type: RSA
certificates_algorithm_size: 4096
certificates_ca_validity_days: 7300
certificates_validity_days: 7300
certificates_renew: false
