---
- name: Backup databases and configuration
  hosts: "{{ target_host | default('quadlet') }}"
  become: true
  gather_facts: true
  vars:
    flavor: katello
  vars_files:
    - "../../vars/defaults.yml"
    - "../../vars/flavors/{{ flavor }}.yml"
    - "../../vars/certificates.yml"
    - "../../vars/images.yml"
    - "../../vars/foreman.yml"
    - "../../vars/database.yml"
    - "../../vars/base.yaml"
  pre_tasks:
    - name: Ensure PostgreSQL client image is available
      containers.podman.podman_image:
        name: "{{ postgresql_container_image }}:{{ postgresql_container_tag }}"
        state: present
        pull: "{{ not (air_gapped | bool) }}"
  roles:
    - role: backup
      vars:
        backup_database_mode: "{{ database_mode }}"
        backup_databases: "{{ all_databases }}"
        backup_pulp_storage_path: "{{ pulp_storage_path }}"
