---
variables:
  certificates_ca_validity_days:
    help: Lifetime of the generated CA certificate, in days.
    parameter: --cert-ca-validity-days
  certificates_validity_days:
    help: Lifetime of the generated server and client certificates, in days.
    parameter: --cert-validity-days
