---
- name: Execute checks
  ansible.builtin.include_tasks: execute_check.yml
  loop: "{{ checks_to_execute }}"

- name: Run cloud connector checks
  ansible.builtin.include_role:
    name: check_cloud_connector
  when: enabled_features | has_feature('cloud-connector')

- name: Run database index integrity checks
  ansible.builtin.include_role:
    name: check_database_index
  vars:
    check_database_index_database: "{{ item.database }}"
  loop: "{{ checks_databases }}"
  no_log: true
  when: database_mode == 'internal'

- name: Report status of checks
  ansible.builtin.fail:
    msg: "{{ checks_results }}"
  when:
    - checks_results|default([])|length > 0
