---
- name: Deploy HTTP proxy configuration for cloud connector dispatcher
  when: cloud_connector_http_proxy is defined
  block:
    - name: Create systemd drop-in directory for cloud connector dispatcher
      ansible.builtin.file:
        state: directory
        path: /etc/systemd/system/{{ cloud_connector_dispatcher_service }}.service.d
        owner: root
        group: root
        mode: '0755'

    - name: Deploy HTTP proxy systemd drop-in for cloud connector dispatcher
      ansible.builtin.template:
        src: proxy.conf.j2
        dest: /etc/systemd/system/{{ cloud_connector_dispatcher_service }}.service.d/proxy.conf
        owner: root
        group: root
        mode: '0640'
      notify: Restart cloud connector dispatcher

- name: Remove HTTP proxy configuration for cloud connector dispatcher
  when: cloud_connector_http_proxy is not defined
  block:
    - name: Remove HTTP proxy systemd drop-in for cloud connector dispatcher
      ansible.builtin.file:
        path: /etc/systemd/system/{{ cloud_connector_dispatcher_service }}.service.d/proxy.conf
        state: absent
      notify: Restart cloud connector dispatcher

    - name: Check if systemd drop-in directory is empty
      ansible.builtin.find:
        paths: /etc/systemd/system/{{ cloud_connector_dispatcher_service }}.service.d
        file_type: any
      register: cloud_connector_dropin_contents

    - name: Remove systemd drop-in directory if empty
      ansible.builtin.file:
        path: /etc/systemd/system/{{ cloud_connector_dispatcher_service }}.service.d
        state: absent
      when: cloud_connector_dropin_contents.matched == 0
