---
- name: Setup OpenVox repositories
  ansible.builtin.include_role:
    name: theforeman.operations.openvox_repositories
  vars:
    foreman_openvox_repositories_version: "{{ setup_repositories_openvox_version }}"

- name: Setup Foreman repositories
  ansible.builtin.include_role:
    name: theforeman.operations.foreman_repositories
  vars:
    foreman_repositories_version: "{{ setup_repositories_version }}"

- name: Setup repository for Katello {{ setup_repositories_version }}
  ansible.builtin.yum_repository:
    name: katello
    description: Katello repository
    gpgcheck: false
    baseurl: "https://yum.theforeman.org/katello/{{ setup_repositories_version }}/katello/el{{ ansible_facts['distribution_major_version'] }}/$basearch/"
  when:
    - ansible_facts['os_family'] == 'RedHat'

- name: Refresh package cache
  ansible.builtin.package:
    update_cache: true
  when:
    - ansible_facts['os_family'] == 'Debian'
