---
- name: Manage services
  hosts: quadlet
  gather_facts: true
  become: true
  vars_files:
    - "../../vars/defaults.yml"
    - "../../vars/database.yml"
  tasks:
    - name: "Manage services"
      ansible.builtin.service:
        name: "{{ item }}"
        state: "{{ 'started' if services_state == 'start' else 'stopped' }}"
      loop:
        - candlepin
        - foreman
        - dynflow-sidekiq@orchestrator
        - dynflow-sidekiq@worker
        - dynflow-sidekiq@worker-hosts-queue
        - pulp-api
        - pulp-content
        - pulp-worker
