---
- name: Manage services
  hosts: quadlet
  gather_facts: true
  become: true
  vars_files:
    - "../../vars/defaults.yml"
    - "../../vars/database.yml"
  tasks:
    - name: "Manage services"
      ansible.builtin.service:
        name: foreman.target
        state: "{{ 'started' if services_state == 'start' else 'stopped' }}"
