---
- name: Check if PG_VERSION file exists
  ansible.builtin.stat:
    path: "{{ postgresql_data_dir }}/userdata/PG_VERSION"
  register: postgresql_version_file

- name: Set postgresql_version version fact
  when: postgresql_version_file.stat.exists
  block:
    - name: Read PG_VERSION file
      ansible.builtin.slurp:
        src: "{{ postgresql_data_dir }}/userdata/PG_VERSION"
      register: postgresql_version_encoded

    - name: Register PG version fact
      ansible.builtin.set_fact:
        postgresql_version: "{{ postgresql_version_encoded.content | b64decode | trim }}"

- name: Upgrade PostgreSQL 13 to 16
  when:
    - "postgresql_version is defined"
    - "postgresql_version == '13'"
  block:
    - name: Stop foreman target
      ansible.builtin.systemd:
        name: foreman.target
        state: stopped
      failed_when: false

    - name: Wait for port 5432 to be completely freed by Podman
      ansible.builtin.wait_for:
        port: 5432
        state: stopped
        timeout: 30

    - name: Deploy PostgreSQL upgrade container
      containers.podman.podman_container:
        name: "{{ postgresql_container_name }}-upgrade"
        image: postgresql.image
        state: quadlet
        sdnotify: false
        volumes:
          - "{{ postgresql_data_dir }}:/var/lib/pgsql/data:rw,Z"
        secrets:
          - 'postgresql-admin-password,target=POSTGRESQL_ADMIN_PASSWORD,type=env'
        env:
          POSTGRESQL_MAX_CONNECTIONS: "{{ postgresql_max_connections }}"
          POSTGRESQL_SHARED_BUFFERS: "{{ postgresql_shared_buffers }}"
          POSTGRESQL_EFFECTIVE_CACHE_SIZE: "{{ postgresql_effective_cache_size }}"
          # explicitly set the previous version to avoid the upgrade failure
          # see https://github.com/sclorg/postgresql-container/issues/661
          POSTGRESQL_PREV_VERSION: "{{ postgresql_version }}"
          POSTGRESQL_UPGRADE: "{{ postgresql_upgrade }}"
        command: "run-postgresql -V"
        quadlet_options:
          - |
            [Unit]
            Description=PostgreSQL Database Upgrade from 13 to 16
            [Service]
            Type=oneshot
            RemainAfterExit=yes
            TimeoutStartSec=30m

    - name: Run daemon reload to make Quadlet create the upgrade service file
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Upgrade the database from 13 to 16 but don't start the server
      ansible.builtin.systemd:
        name: "{{ postgresql_container_name }}-upgrade.service"
        state: restarted

    - name: Remove the quadlet file
      ansible.builtin.file:
        path: "/etc/containers/systemd/{{ postgresql_container_name }}-upgrade.container"
        state: absent

    - name: Reload systemd
      ansible.builtin.systemd_service:
        daemon_reload: true
