---
candlepin_ssl_port: 23443
candlepin_hostname: localhost
candlepin_tls_versions:
  - "TLSv1.2"
candlepin_ciphers:
  - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256
candlepin_container_image: quay.io/foreman/candlepin
candlepin_container_tag: "4.4.14"

candlepin_database_host: localhost
candlepin_database_port: 5432
candlepin_database_ssl: false
candlepin_database_ssl_mode: disable
candlepin_database_ssl_ca:
candlepin_database_ssl_cert:
candlepin_database_ssl_key:
