---
- name: List features
  hosts: quadlet
  gather_facts: false
  tags:
    - foremanctl_suppress_default_output
  vars:
    flavor: katello
    list_enabled: false
  vars_files:
    - "../../vars/defaults.yml"
    - "../../vars/flavors/{{ flavor }}.yml"
    - "../../vars/base.yaml"
  tasks:
    - name: Check whether a deployment has completed
      ansible.builtin.stat:
        path: "{{ obsah_state_path }}/.installed"
      delegate_to: localhost
      become: false
      register: foremanctl_deployment

    - name: Print features
      ansible.builtin.debug:
        msg: >-
          {{ enabled_features | list_all_features(
            list_enabled,
            flavor if foremanctl_deployment.stat.exists else none
          ) }}
