---
- name: Deploy debug_tools
  ansible.builtin.include_role:
    name: debug_tools

- name: 'Enable postgresql:16 module'
  ansible.builtin.command: dnf module enable -y postgresql:16
  # can't use the `dnf` module for modules without a default stream
  # https://github.com/ansible/ansible/issues/56504
  # https://github.com/ansible/ansible/issues/64852
  args:
    creates: /etc/dnf/modules.d/postgresql.module
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['distribution_major_version'] == '9'

- name: Install podman and utilities
  ansible.builtin.package:
    name:
      - podman
      - skopeo

- name: Install other dependencies
  ansible.builtin.package:
    name:
      - bash-completion
      - python3-cryptography
      - python3-libsemanage
      - python3-psycopg2
      - python3-requests
      - python3-requests-oauthlib
