---
- name: Setup machine
  hosts:
    - "{{ foremanctl_target | default('quadlet') }}"
  become: true
  vars_files:
    - "../../vars/defaults.yml"
    - "../../vars/flavors/{{ flavor }}.yml"
    - "../../vars/certificates.yml"
    - "../../vars/images.yml"
    - "../../vars/tuning/{{ tuning }}.yml"
    - "../../vars/database.yml"
    - "../../vars/foreman.yml"
    - "../../vars/base.yaml"
  roles:
    - role: pre_install
    - role: checks
      vars:
        checks_databases: "{{ all_databases }}"
    # TODO: Add tar_file check/extractation step for certificates_source == 'proxy'
    - role: certificates
      when: "certificates_source in ['default', 'custom_server']"
    # TODO: remove proxy condition and add tar check
    - role: certificate_checks
      vars:
        certificate_checks_certificate: "{{ server_certificate }}"
        certificate_checks_key: "{{ server_key }}"
        certificate_checks_ca: "{{ server_ca_certificate }}"
    - role: postgresql
      when: database_mode == 'internal'
    - redis
    - role: candlepin
      when: enabled_features | has_feature('candlepin')
    - httpd
    - role: pulp
      when: enabled_features | has_feature('pulp')
    - role: foreman
      when: "'foreman' in enabled_features"
    - role: systemd_target
    - role: iop_core
      when:
        - "'iop' in enabled_features"
        - database_mode == 'internal'
    - role: foreman_proxy
      when:
        - "'foreman-proxy' in enabled_features"
    - role: hammer
      when:
        - "'hammer' in enabled_features"
    - role: post_install
