---
- name: Setup machine
  hosts:
    - quadlet
  become: true
  vars:
    flavor: katello
  vars_files:
    - "../../vars/defaults.yml"
    - "../../vars/flavors/{{ flavor }}.yml"
    - "../../vars/certificates.yml"
    - "../../vars/images.yml"
    - "../../vars/tuning/{{ tuning }}.yml"
    - "../../vars/database.yml"
    - "../../vars/foreman.yml"
    - "../../vars/logging.yml"
    - "../../vars/base.yaml"
  roles:
    - role: pre_install
    - role: checks
      vars:
        checks_databases: "{{ all_databases }}"
    - role: certificates
    - role: certificate_checks
      vars:
        certificate_checks_certificate: "{{ server_certificate }}"
        certificate_checks_key: "{{ server_key }}"
        certificate_checks_ca: "{{ server_ca_certificate }}"
    - role: postgresql
      when:
        - database_mode == 'internal'
    - valkey
    - candlepin
    - httpd
    - foreman
    - pulp
    - role: systemd_target
    - role: iop_core
      when:
        - "enabled_features | has_feature('iop')"
        - database_mode == 'internal'
    - role: foreman_proxy
      when:
        - "enabled_features | has_feature('foreman-proxy')"
    - role: hammer
      when:
        - "enabled_features | has_feature('hammer')"
    - role: post_install
      vars:
        post_install_foreman_ca_path: "{{ foreman_ca_certificate }}"
        post_install_foreman_oauth_consumer_key: "{{ foreman_oauth_consumer_key }}"
        post_install_foreman_oauth_consumer_secret: "{{ foreman_oauth_consumer_secret }}"
        post_install_foreman_server_url: "{{ foreman_url }}"
        post_install_foreman_initial_admin_password: "{{ foreman_initial_admin_password }}"
        post_install_foreman_initial_admin_username: "{{ foreman_initial_admin_username }}"
