---
help: |
  Install

  foreman_admin_username:
    help: Initial username for the admin user.
  foreman_admin_password:
    help: Initial password for the admin user.
include:
  - _certificate_source
  - _database_mode
  - _database_connection
