---
help: |
  Install Server

variables:
  flavor:
    help: Base flavor to use in this deployment.
    choices:
      - katello
  external_authentication:
    help: External authentication method to use
    choices:
      - ipa
      - ipa_with_api
  external_authentication_pam_service:
    help: Name of the PAM service to use for IPA authentication
  foreman_log_level:
    help: Log level for Foreman. Defaults to the global log level.
    choices:
      - debug
      - info
      - warn
      - error
      - fatal
  cloud_connector_http_proxy:
    parameter: --cloud-connector-http-proxy
    help: HTTP proxy URL for the cloud connector rhcd service.

include:
  - _flavor_features
  - _flavors/katello
