---
help: |
  Install Server

variables:
  flavor:
    help: Base flavor to use in this deployment.
    choices:
      - katello
  external_authentication:
    help: External authentication method to use
    choices:
      - ipa
      - ipa_with_api
  external_authentication_pam_service:
    help: Name of the PAM service to use for IPA authentication
  foreman_log_level:
    help: Log level for Foreman. Defaults to the global log level.
    choices:
      - debug
      - info
      - warn
      - error
      - fatal

include:
  - _flavor_features
  - _flavors/katello
  - _vendor_override
