---
variables:
  certificates_source:
    help: Where certificates are coming from. Currently default Ansible role, the foreman-installer, or custom server certificates.
    parameter: --certificate-source
    choices:
      - default
      - installer
      - custom_server
