---
variables:
  certificates_source:
    help: Where certificates are coming from. Currently default Ansible role or custom server certificates.
    parameter: --certificate-source
    choices:
      - default
      - custom_server
