---
- name: Deploy iop-advisor image unit
  ansible.builtin.include_role:
    name: images
    tasks_from: deploy_image.yaml
  vars:
    images_definition:
      name: iop-advisor
      image: "{{ iop_advisor_container_image }}:{{ iop_advisor_container_tag }}"
