---
foreman_development_user: "vagrant"
foreman_development_group: "{{ foreman_development_user }}"
foreman_development_deployment_dir: "/home/{{ foreman_development_user }}"
foreman_development_foreman_dir: "{{ foreman_development_deployment_dir }}/foreman"
foreman_development_cert_dir: "{{ foreman_development_deployment_dir }}/foreman-certs"
foreman_development_hammer_dir: "{{ foreman_development_deployment_dir }}/hammer-cli"
foreman_development_smart_proxy_dir: "{{ foreman_development_deployment_dir }}/smart-proxy"

foreman_development_ca_certificate: "{{ foreman_ca_certificate }}"
foreman_development_client_certificate: "{{ foreman_client_certificate }}"
foreman_development_client_key: "{{ foreman_client_key }}"

foreman_development_admin_user: "admin"
foreman_development_admin_password: "changeme"

foreman_development_git_repo: "https://github.com/theforeman/foreman.git"
foreman_development_git_revision: "develop"
foreman_development_github_username: ""

foreman_development_hammer_git_repo: "https://github.com/theforeman/hammer-cli.git"

foreman_development_smart_proxy_git_repo: "https://github.com/theforeman/smart-proxy.git"

foreman_development_rails_port: 3000
foreman_development_rails_command: "puma -w 2 -p {{ foreman_development_rails_port }} --preload -b tcp://0.0.0.0"

foreman_development_url: "http://{{ ansible_facts['fqdn'] }}:{{ foreman_development_rails_port }}"

foreman_development_database_host: "localhost"
foreman_development_database_port: 5432
foreman_development_database_name: "foreman_development"
foreman_development_database_user: "foreman"
foreman_development_database_password: "foreman"

foreman_development_nodejs_stream: "22"

foreman_development_default_features:
  - katello
  - remote-execution

foreman_development_packages:
  - git
  - ruby-devel
  - npm
  - postgresql-devel
  - libxml2-devel
  - libxslt-devel
  - libcurl-devel
  - libffi-devel
  - gcc-c++
  - make
  - rubygem-bundler
  - rubygem-irb
  - postgresql
