---
- name: Create the podman secret for Smart Proxy CA certificate
  containers.podman.podman_secret:
    name: smart-proxy-ssl-ca
    path: "{{ server_ca_certificate }}"
    state: present
  notify:
    - Restart Smart Proxy

- name: Create the podman secret for Smart Proxy server key (for HTTPS)
  containers.podman.podman_secret:
    state: present
    name: smart-proxy-ssl-key
    path: "{{ server_key }}"
  notify:
    - Restart Smart Proxy

- name: Create the podman secret for Smart Proxy server certificate (for HTTPS)
  containers.podman.podman_secret:
    state: present
    name: smart-proxy-ssl-cert
    path: "{{ server_certificate }}"
  notify:
    - Restart Smart Proxy

- name: Create the podman secret for Smart Proxy Foreman client key
  containers.podman.podman_secret:
    state: present
    name: smart-proxy-foreman-ssl-key
    path: "{{ client_key }}"
  notify:
    - Restart Smart Proxy

- name: Create the podman secret for Smart Proxy Foreman client certificate
  containers.podman.podman_secret:
    state: present
    name: smart-proxy-foreman-ssl-cert
    path: "{{ client_certificate }}"
  notify:
    - Restart Smart Proxy
