---
- name: Deploy iop-kafka image unit
  ansible.builtin.include_role:
    name: images
    tasks_from: deploy_image.yaml
  vars:
    images_definition:
      name: iop-kafka
      image: "{{ iop_kafka_container_image }}:{{ iop_kafka_container_tag }}"
