collections:
  - community.postgresql
  - community.crypto
  - community.general
  - ansible.posix
  - name: containers.podman
    version: ">=1.19.0"
  - name: theforeman.foreman
    version: ">=5.11.0"
