collections:
  - name: community.postgresql
    version: ">=4.0.0"
  - community.crypto
  - community.general
  - ansible.posix
  - name: containers.podman
    version: ">=1.19.0"
  - name: theforeman.foreman
    version: ">=5.11.0"
