---
help: |
  Install Proxy

variables:
  flavor:
    help: Base flavor to use in this deployment.
    choices:
      - foreman-proxy-content
  certificates_bundle:
    help: Path to the certificate bundle tar file.
    type: AbsolutePath
    parameter: --certificate-bundle
    persist: false
  foreman_name:
    parameter: --foreman-fqdn
    help: FQDN of the Foreman server this proxy connects to.

include:
  - _flavor_features
  - _flavors/foreman-proxy-content
