---
- name: Get all Foreman target services as JSON
  ansible.builtin.shell:
    cmd: systemctl list-units --output=json --all $(systemctl list-dependencies --plain foreman.target)
  register: check_services_all_json
  changed_when: false
  tags:
    - skip_ansible_lint  # Skipping linting; systemctl JSON output not available via systemd module

- name: Filter out foreman-recurring services
  ansible.builtin.set_fact:
    check_services_all_list: >-
      {{
        (check_services_all_json.stdout | from_json) |
        selectattr('unit', 'search', '\.service$') |
        rejectattr('unit', 'search', 'foreman-recurring@') |
        list
      }}

- name: Determine Foreman services which are inactive
  ansible.builtin.set_fact:
    check_services_not_running_list: >-
      {{
        check_services_all_list |
        rejectattr('active', 'equalto', 'active') |
        list
      }}

- name: Verify all Foreman target services are active
  ansible.builtin.assert:
    that:
      - check_services_not_running_list | length == 0
    fail_msg: |-
      Some services are not running:

      {% for service in check_services_not_running_list %}
      - {{ service.unit.split('.')[0] }}: {{ service.active }} ({{ service.sub }})
      {% endfor %}
    success_msg: |-
      All services are running:

      {% for service in check_services_all_list %}
      - {{ service.unit.split('.')[0] }}: {{ service.active }}
      {% endfor %}
