---
- name: Restart Foreman Proxy
  environment:
    XDG_RUNTIME_DIR: "{{ foremanctl_xdg_runtime_dir }}"
  become: true
  become_user: "{{ foremanctl_user }}"
  ansible.builtin.systemd:
    name: foreman-proxy
    state: restarted
    scope: user

- name: Refresh Foreman Proxy
  theforeman.foreman.smart_proxy_refresh:
    smart_proxy: "{{ foreman_proxy_name }}"
    server_url: "{{ foreman_url }}"
    username: "{{ foreman_initial_admin_username }}"
    password: "{{ foreman_initial_admin_password }}"
    validate_certs: false
