---
- name: Run Foreman health checks
  hosts: "{{ target_host | default('quadlet') }}"
  become: true
  gather_facts: true
  vars:
    flavor: katello
  vars_files:
    - "../../vars/defaults.yml"
    - "../../vars/flavors/{{ flavor }}.yml"
    - "../../vars/base.yaml"
    - "../../vars/database.yml"
  tasks:
    - name: Execute health checks
      ansible.builtin.include_role:
        name: checks
        tasks_from: execute_check
      loop: "{{ health_checks_to_execute }}"
      when: >-
        (item != 'check_foreman_tasks' or not (health_skip_check_foreman_tasks_param | default(false) | bool))
      # Add additional skips here

    - name: Report status of health checks
      ansible.builtin.fail:
        msg: "{{ checks_results }}"
      when:
        - checks_results|default([])|length > 0
